/**
 * S-57 Attribute Catalogue.
 *
 * Maps numeric ATTL codes to attribute names, types, and descriptions.
 * Based on IHO S-57 Object Catalogue (Appendix A, Chapter 2).
 */

/** Attribute value type in the catalogue */
export type AttrValueType = 'string' | 'int' | 'float' | 'enum' | 'list';

export interface AttributeDef {
  /** ATTL numeric code */
  code: number;
  /** Six-character acronym (e.g. "DRVAL1") */
  acronym: string;
  /** Value type */
  valueType: AttrValueType;
  /** Human-readable name */
  name: string;
}

/**
 * S-57 attribute definitions (IHO S-57 Edition 3.1, Appendix A, Chapter 2).
 * Codes, acronyms, types and names as in the IHO catalogue; the same table
 * GDAL and OpenCPN ship as s57attributes.csv.
 */
export const S57_ATTRIBUTES: ReadonlyMap<number, AttributeDef> = new Map([
  [1, { code: 1, acronym: 'AGENCY', valueType: 'string', name: 'Agency responsible for production' }],
  [2, { code: 2, acronym: 'BCNSHP', valueType: 'enum', name: 'Beacon shape' }],
  [3, { code: 3, acronym: 'BUISHP', valueType: 'enum', name: 'Building shape' }],
  [4, { code: 4, acronym: 'BOYSHP', valueType: 'enum', name: 'Buoy shape' }],
  [5, { code: 5, acronym: 'BURDEP', valueType: 'float', name: 'Buried depth' }],
  [6, { code: 6, acronym: 'CALSGN', valueType: 'string', name: 'Call sign' }],
  [7, { code: 7, acronym: 'CATAIR', valueType: 'list', name: 'Category of airport/airfield' }],
  [8, { code: 8, acronym: 'CATACH', valueType: 'list', name: 'Category of anchorage' }],
  [9, { code: 9, acronym: 'CATBRG', valueType: 'list', name: 'Category of bridge' }],
  [10, { code: 10, acronym: 'CATBUA', valueType: 'enum', name: 'Category of built-up area' }],
  [11, { code: 11, acronym: 'CATCBL', valueType: 'enum', name: 'Category of cable' }],
  [12, { code: 12, acronym: 'CATCAN', valueType: 'enum', name: 'Category of canal' }],
  [13, { code: 13, acronym: 'CATCAM', valueType: 'enum', name: 'Category of cardinal mark' }],
  [14, { code: 14, acronym: 'CATCHP', valueType: 'enum', name: 'Category of checkpoint' }],
  [15, { code: 15, acronym: 'CATCOA', valueType: 'enum', name: 'Category of coastline' }],
  [16, { code: 16, acronym: 'CATCTR', valueType: 'enum', name: 'Category of control point' }],
  [17, { code: 17, acronym: 'CATCON', valueType: 'enum', name: 'Category of conveyor' }],
  [18, { code: 18, acronym: 'CATCOV', valueType: 'enum', name: 'Category of coverage' }],
  [19, { code: 19, acronym: 'CATCRN', valueType: 'enum', name: 'Category of crane' }],
  [20, { code: 20, acronym: 'CATDAM', valueType: 'enum', name: 'Category of dam' }],
  [21, { code: 21, acronym: 'CATDIS', valueType: 'enum', name: 'Category of distance mark' }],
  [22, { code: 22, acronym: 'CATDOC', valueType: 'enum', name: 'Category of dock' }],
  [23, { code: 23, acronym: 'CATDPG', valueType: 'list', name: 'Category of dumping ground' }],
  [24, { code: 24, acronym: 'CATFNC', valueType: 'enum', name: 'Category of fence/wall' }],
  [25, { code: 25, acronym: 'CATFRY', valueType: 'enum', name: 'Category of ferry' }],
  [26, { code: 26, acronym: 'CATFIF', valueType: 'enum', name: 'Category of fishing facility' }],
  [27, { code: 27, acronym: 'CATFOG', valueType: 'enum', name: 'Category of fog signal' }],
  [28, { code: 28, acronym: 'CATFOR', valueType: 'enum', name: 'Category of fortified structure' }],
  [29, { code: 29, acronym: 'CATGAT', valueType: 'enum', name: 'Category of gate' }],
  [30, { code: 30, acronym: 'CATHAF', valueType: 'list', name: 'Category of harbour facility' }],
  [31, { code: 31, acronym: 'CATHLK', valueType: 'list', name: 'Category of hulk' }],
  [32, { code: 32, acronym: 'CATICE', valueType: 'enum', name: 'Category of ice' }],
  [33, { code: 33, acronym: 'CATINB', valueType: 'enum', name: 'Category of installation buoy' }],
  [34, { code: 34, acronym: 'CATLND', valueType: 'list', name: 'Category of land region' }],
  [35, { code: 35, acronym: 'CATLMK', valueType: 'list', name: 'Category of landmark' }],
  [36, { code: 36, acronym: 'CATLAM', valueType: 'enum', name: 'Category of lateral mark' }],
  [37, { code: 37, acronym: 'CATLIT', valueType: 'list', name: 'Category of light' }],
  [38, { code: 38, acronym: 'CATMFA', valueType: 'enum', name: 'Category of marine farm/culture' }],
  [39, { code: 39, acronym: 'CATMPA', valueType: 'list', name: 'Category of military practice area' }],
  [40, { code: 40, acronym: 'CATMOR', valueType: 'enum', name: 'Category of mooring/warping facility' }],
  [41, { code: 41, acronym: 'CATNAV', valueType: 'enum', name: 'Category of navigation line' }],
  [42, { code: 42, acronym: 'CATOBS', valueType: 'enum', name: 'Category of obstruction' }],
  [43, { code: 43, acronym: 'CATOFP', valueType: 'list', name: 'Category of offshore platform' }],
  [44, { code: 44, acronym: 'CATOLB', valueType: 'enum', name: 'Category of oil barrier' }],
  [45, { code: 45, acronym: 'CATPLE', valueType: 'enum', name: 'Category of pile' }],
  [46, { code: 46, acronym: 'CATPIL', valueType: 'enum', name: 'Category of pilot boarding place' }],
  [47, { code: 47, acronym: 'CATPIP', valueType: 'list', name: 'Category of pipeline / pipe' }],
  [48, { code: 48, acronym: 'CATPRA', valueType: 'enum', name: 'Category of production area' }],
  [49, { code: 49, acronym: 'CATPYL', valueType: 'enum', name: 'Category of pylon' }],
  [50, { code: 50, acronym: 'CATQUA', valueType: 'enum', name: 'Category of quality of data' }],
  [51, { code: 51, acronym: 'CATRAS', valueType: 'enum', name: 'Category of radar station' }],
  [52, { code: 52, acronym: 'CATRTB', valueType: 'enum', name: 'Category of radar transponder beacon' }],
  [53, { code: 53, acronym: 'CATROS', valueType: 'list', name: 'Category of radio station' }],
  [54, { code: 54, acronym: 'CATTRK', valueType: 'enum', name: 'Category of recommended track' }],
  [55, { code: 55, acronym: 'CATRSC', valueType: 'list', name: 'Category of rescue station' }],
  [56, { code: 56, acronym: 'CATREA', valueType: 'list', name: 'Category of restricted area' }],
  [57, { code: 57, acronym: 'CATROD', valueType: 'enum', name: 'Category of road' }],
  [58, { code: 58, acronym: 'CATRUN', valueType: 'enum', name: 'Category of runway' }],
  [59, { code: 59, acronym: 'CATSEA', valueType: 'enum', name: 'Category of sea area' }],
  [60, { code: 60, acronym: 'CATSLC', valueType: 'enum', name: 'Category of shoreline construction' }],
  [61, { code: 61, acronym: 'CATSIT', valueType: 'list', name: 'Category of signal station - traffic' }],
  [62, { code: 62, acronym: 'CATSIW', valueType: 'list', name: 'Category of signal station - warning' }],
  [63, { code: 63, acronym: 'CATSIL', valueType: 'enum', name: 'Category of silo/tank' }],
  [64, { code: 64, acronym: 'CATSLO', valueType: 'enum', name: 'Category of slope' }],
  [65, { code: 65, acronym: 'CATSCF', valueType: 'list', name: 'Category of small craft facility' }],
  [66, { code: 66, acronym: 'CATSPM', valueType: 'list', name: 'Category of special purpose mark' }],
  [67, { code: 67, acronym: 'CATTSS', valueType: 'enum', name: 'Category of Traffic Separation Scheme' }],
  [68, { code: 68, acronym: 'CATVEG', valueType: 'list', name: 'Category of vegetation' }],
  [69, { code: 69, acronym: 'CATWAT', valueType: 'enum', name: 'Category of water turbulence' }],
  [70, { code: 70, acronym: 'CATWED', valueType: 'enum', name: 'Category of weed/kelp' }],
  [71, { code: 71, acronym: 'CATWRK', valueType: 'enum', name: 'Category of wreck' }],
  [72, { code: 72, acronym: 'CATZOC', valueType: 'enum', name: 'Category of zone of confidence data' }],
  [73, { code: 73, acronym: '$SPACE', valueType: 'enum', name: 'Character spacing' }],
  [74, { code: 74, acronym: '$CHARS', valueType: 'string', name: 'Character specification' }],
  [75, { code: 75, acronym: 'COLOUR', valueType: 'list', name: 'Colour' }],
  [76, { code: 76, acronym: 'COLPAT', valueType: 'list', name: 'Colour pattern' }],
  [77, { code: 77, acronym: 'COMCHA', valueType: 'string', name: 'Communication channel' }],
  [78, { code: 78, acronym: '$CSIZE', valueType: 'float', name: 'Compass size' }],
  [79, { code: 79, acronym: 'CPDATE', valueType: 'string', name: 'Compilation date' }],
  [80, { code: 80, acronym: 'CSCALE', valueType: 'int', name: 'Compilation scale' }],
  [81, { code: 81, acronym: 'CONDTN', valueType: 'enum', name: 'Condition' }],
  [82, { code: 82, acronym: 'CONRAD', valueType: 'enum', name: 'Conspicuous - Radar' }],
  [83, { code: 83, acronym: 'CONVIS', valueType: 'enum', name: 'Conspicuous - Visual' }],
  [84, { code: 84, acronym: 'CURVEL', valueType: 'float', name: 'Current velocity' }],
  [85, { code: 85, acronym: 'DATEND', valueType: 'string', name: 'Date end' }],
  [86, { code: 86, acronym: 'DATSTA', valueType: 'string', name: 'Date start' }],
  [87, { code: 87, acronym: 'DRVAL1', valueType: 'float', name: 'Depth range value 1' }],
  [88, { code: 88, acronym: 'DRVAL2', valueType: 'float', name: 'Depth range value 2' }],
  [89, { code: 89, acronym: 'DUNITS', valueType: 'enum', name: 'Depth units' }],
  [90, { code: 90, acronym: 'ELEVAT', valueType: 'float', name: 'Elevation' }],
  [91, { code: 91, acronym: 'ESTRNG', valueType: 'float', name: 'Estimated range of transmission' }],
  [92, { code: 92, acronym: 'EXCLIT', valueType: 'enum', name: 'Exhibition condition of light' }],
  [93, { code: 93, acronym: 'EXPSOU', valueType: 'enum', name: 'Exposition of sounding' }],
  [94, { code: 94, acronym: 'FUNCTN', valueType: 'list', name: 'Function' }],
  [95, { code: 95, acronym: 'HEIGHT', valueType: 'float', name: 'Height' }],
  [96, { code: 96, acronym: 'HUNITS', valueType: 'enum', name: 'Height/length units' }],
  [97, { code: 97, acronym: 'HORACC', valueType: 'float', name: 'Horizontal accuracy' }],
  [98, { code: 98, acronym: 'HORCLR', valueType: 'float', name: 'Horizontal clearance' }],
  [99, { code: 99, acronym: 'HORLEN', valueType: 'float', name: 'Horizontal length' }],
  [100, { code: 100, acronym: 'HORWID', valueType: 'float', name: 'Horizontal width' }],
  [101, { code: 101, acronym: 'ICEFAC', valueType: 'float', name: 'Ice factor' }],
  [102, { code: 102, acronym: 'INFORM', valueType: 'string', name: 'Information' }],
  [103, { code: 103, acronym: 'JRSDTN', valueType: 'enum', name: 'Jurisdiction' }],
  [104, { code: 104, acronym: '$JUSTH', valueType: 'enum', name: 'Justification - horizontal' }],
  [105, { code: 105, acronym: '$JUSTV', valueType: 'enum', name: 'Justification - vertical' }],
  [106, { code: 106, acronym: 'LIFCAP', valueType: 'float', name: 'Lifting capacity' }],
  [107, { code: 107, acronym: 'LITCHR', valueType: 'enum', name: 'Light characteristic' }],
  [108, { code: 108, acronym: 'LITVIS', valueType: 'list', name: 'Light visibility' }],
  [109, { code: 109, acronym: 'MARSYS', valueType: 'enum', name: 'Marks navigational - System of' }],
  [110, { code: 110, acronym: 'MLTYLT', valueType: 'int', name: 'Multiplicity of lights' }],
  [111, { code: 111, acronym: 'NATION', valueType: 'string', name: 'Nationality' }],
  [112, { code: 112, acronym: 'NATCON', valueType: 'list', name: 'Nature of construction' }],
  [113, { code: 113, acronym: 'NATSUR', valueType: 'list', name: 'Nature of surface' }],
  [114, { code: 114, acronym: 'NATQUA', valueType: 'list', name: 'Nature of surface - qualifying terms' }],
  [115, { code: 115, acronym: 'NMDATE', valueType: 'string', name: 'Notice to Mariners date' }],
  [116, { code: 116, acronym: 'OBJNAM', valueType: 'string', name: 'Object name' }],
  [117, { code: 117, acronym: 'ORIENT', valueType: 'float', name: 'Orientation' }],
  [118, { code: 118, acronym: 'PEREND', valueType: 'string', name: 'Periodic date end' }],
  [119, { code: 119, acronym: 'PERSTA', valueType: 'string', name: 'Periodic date start' }],
  [120, { code: 120, acronym: 'PICREP', valueType: 'string', name: 'Pictorial representation' }],
  [121, { code: 121, acronym: 'PILDST', valueType: 'string', name: 'Pilot district' }],
  [122, { code: 122, acronym: 'PRCTRY', valueType: 'string', name: 'Producing country' }],
  [123, { code: 123, acronym: 'PRODCT', valueType: 'list', name: 'Product' }],
  [124, { code: 124, acronym: 'PUBREF', valueType: 'string', name: 'Publication reference' }],
  [125, { code: 125, acronym: 'QUASOU', valueType: 'list', name: 'Quality of sounding measurement' }],
  [126, { code: 126, acronym: 'RADWAL', valueType: 'string', name: 'Radar wave length' }],
  [127, { code: 127, acronym: 'RADIUS', valueType: 'float', name: 'Radius' }],
  [128, { code: 128, acronym: 'RECDAT', valueType: 'string', name: 'Recording date' }],
  [129, { code: 129, acronym: 'RECIND', valueType: 'string', name: 'Recording indication' }],
  [130, { code: 130, acronym: 'RYRMGV', valueType: 'string', name: 'Reference year for magnetic variation' }],
  [131, { code: 131, acronym: 'RESTRN', valueType: 'list', name: 'Restriction' }],
  [132, { code: 132, acronym: 'SCAMAX', valueType: 'int', name: 'Scale maximum' }],
  [133, { code: 133, acronym: 'SCAMIN', valueType: 'int', name: 'Scale minimum' }],
  [134, { code: 134, acronym: 'SCVAL1', valueType: 'int', name: 'Scale value one' }],
  [135, { code: 135, acronym: 'SCVAL2', valueType: 'int', name: 'Scale value two' }],
  [136, { code: 136, acronym: 'SECTR1', valueType: 'float', name: 'Sector limit one' }],
  [137, { code: 137, acronym: 'SECTR2', valueType: 'float', name: 'Sector limit two' }],
  [138, { code: 138, acronym: 'SHIPAM', valueType: 'string', name: 'Shift parameters' }],
  [139, { code: 139, acronym: 'SIGFRQ', valueType: 'int', name: 'Signal frequency' }],
  [140, { code: 140, acronym: 'SIGGEN', valueType: 'enum', name: 'Signal generation' }],
  [141, { code: 141, acronym: 'SIGGRP', valueType: 'string', name: 'Signal group' }],
  [142, { code: 142, acronym: 'SIGPER', valueType: 'float', name: 'Signal period' }],
  [143, { code: 143, acronym: 'SIGSEQ', valueType: 'string', name: 'Signal sequence' }],
  [144, { code: 144, acronym: 'SOUACC', valueType: 'float', name: 'Sounding accuracy' }],
  [145, { code: 145, acronym: 'SDISMX', valueType: 'int', name: 'Sounding distance - maximum' }],
  [146, { code: 146, acronym: 'SDISMN', valueType: 'int', name: 'Sounding distance - minimum' }],
  [147, { code: 147, acronym: 'SORDAT', valueType: 'string', name: 'Source date' }],
  [148, { code: 148, acronym: 'SORIND', valueType: 'string', name: 'Source indication' }],
  [149, { code: 149, acronym: 'STATUS', valueType: 'list', name: 'Status' }],
  [150, { code: 150, acronym: 'SURATH', valueType: 'string', name: 'Survey authority' }],
  [151, { code: 151, acronym: 'SUREND', valueType: 'string', name: 'Survey date - end' }],
  [152, { code: 152, acronym: 'SURSTA', valueType: 'string', name: 'Survey date - start' }],
  [153, { code: 153, acronym: 'SURTYP', valueType: 'list', name: 'Survey type' }],
  [154, { code: 154, acronym: '$SCALE', valueType: 'float', name: 'Symbol scaling factor' }],
  [155, { code: 155, acronym: '$SCODE', valueType: 'string', name: 'Symbolization code' }],
  [156, { code: 156, acronym: 'TECSOU', valueType: 'list', name: 'Technique of sounding measurement' }],
  [157, { code: 157, acronym: '$TXSTR', valueType: 'string', name: 'Text string' }],
  [158, { code: 158, acronym: 'TXTDSC', valueType: 'string', name: 'Textual description' }],
  [159, { code: 159, acronym: 'TS_TSP', valueType: 'string', name: 'Tidal stream - panel values' }],
  [160, { code: 160, acronym: 'TS_TSV', valueType: 'string', name: 'Tidal stream current - time series values' }],
  [161, { code: 161, acronym: 'T_ACWL', valueType: 'enum', name: 'Tide - accuracy of water level' }],
  [162, { code: 162, acronym: 'T_HWLW', valueType: 'string', name: 'Tide - high and low water values' }],
  [163, { code: 163, acronym: 'T_MTOD', valueType: 'enum', name: 'Tide - method of tidal prediction' }],
  [164, { code: 164, acronym: 'T_THDF', valueType: 'string', name: 'Tide - time and height differences' }],
  [165, { code: 165, acronym: 'T_TINT', valueType: 'int', name: 'Tide current - time interval of values' }],
  [166, { code: 166, acronym: 'T_TSVL', valueType: 'string', name: 'Tide - time series values' }],
  [167, { code: 167, acronym: 'T_VAHC', valueType: 'string', name: 'Tide - value of harmonic constituents' }],
  [168, { code: 168, acronym: 'TIMEND', valueType: 'string', name: 'Time end' }],
  [169, { code: 169, acronym: 'TIMSTA', valueType: 'string', name: 'Time start' }],
  [170, { code: 170, acronym: '$TINTS', valueType: 'enum', name: 'Tint' }],
  [171, { code: 171, acronym: 'TOPSHP', valueType: 'enum', name: 'Topmark/daymark shape' }],
  [172, { code: 172, acronym: 'TRAFIC', valueType: 'enum', name: 'Traffic flow' }],
  [173, { code: 173, acronym: 'VALACM', valueType: 'float', name: 'Value of annual change in magnetic variation' }],
  [174, { code: 174, acronym: 'VALDCO', valueType: 'float', name: 'Value of depth contour' }],
  [175, { code: 175, acronym: 'VALLMA', valueType: 'float', name: 'Value of local magnetic anomaly' }],
  [176, { code: 176, acronym: 'VALMAG', valueType: 'float', name: 'Value of magnetic variation' }],
  [177, { code: 177, acronym: 'VALMXR', valueType: 'float', name: 'Value of maximum range' }],
  [178, { code: 178, acronym: 'VALNMR', valueType: 'float', name: 'Value of nominal range' }],
  [179, { code: 179, acronym: 'VALSOU', valueType: 'float', name: 'Value of sounding' }],
  [180, { code: 180, acronym: 'VERACC', valueType: 'float', name: 'Vertical accuracy' }],
  [181, { code: 181, acronym: 'VERCLR', valueType: 'float', name: 'Vertical clearance' }],
  [182, { code: 182, acronym: 'VERCCL', valueType: 'float', name: 'Vertical clearance - closed' }],
  [183, { code: 183, acronym: 'VERCOP', valueType: 'float', name: 'Vertical clearance - open' }],
  [184, { code: 184, acronym: 'VERCSA', valueType: 'float', name: 'Vertical clearance - safe' }],
  [185, { code: 185, acronym: 'VERDAT', valueType: 'enum', name: 'Vertical datum' }],
  [186, { code: 186, acronym: 'VERLEN', valueType: 'float', name: 'Vertical length' }],
  [187, { code: 187, acronym: 'WATLEV', valueType: 'enum', name: 'Water level effect' }],
  [188, { code: 188, acronym: 'CAT_TS', valueType: 'enum', name: 'Category of Tidal stream' }],
  [189, { code: 189, acronym: 'PUNITS', valueType: 'enum', name: 'Positional accuracy units' }],
  [190, { code: 190, acronym: 'CLSDEF', valueType: 'string', name: 'Object class definition' }],
  [191, { code: 191, acronym: 'CLSNAM', valueType: 'string', name: 'Object class name' }],
  [192, { code: 192, acronym: 'SYMINS', valueType: 'string', name: 'Symbol instruction' }],
  [300, { code: 300, acronym: 'NINFOM', valueType: 'string', name: 'Information in national language' }],
  [301, { code: 301, acronym: 'NOBJNM', valueType: 'string', name: 'Object name in national language' }],
  [302, { code: 302, acronym: 'NPLDST', valueType: 'string', name: 'Pilot district in national language' }],
  [303, { code: 303, acronym: '$NTXST', valueType: 'string', name: 'Text string in national language' }],
  [304, { code: 304, acronym: 'NTXTDS', valueType: 'string', name: 'Textual description in national language' }],
  [400, { code: 400, acronym: 'HORDAT', valueType: 'enum', name: 'Horizontal datum' }],
  [401, { code: 401, acronym: 'POSACC', valueType: 'float', name: 'Positional Accuracy' }],
  [402, { code: 402, acronym: 'QUAPOS', valueType: 'enum', name: 'Quality of position' }],
  [17000, { code: 17000, acronym: 'catach', valueType: 'list', name: 'Category of anchorage' }],
  [17001, { code: 17001, acronym: 'catdis', valueType: 'enum', name: 'Category of distance mark' }],
  [17002, { code: 17002, acronym: 'catsit', valueType: 'list', name: 'Category of signal station. traffic' }],
  [17003, { code: 17003, acronym: 'catsiw', valueType: 'list', name: 'Category of signal station. warning' }],
  [17004, { code: 17004, acronym: 'restrn', valueType: 'list', name: 'Restriction' }],
  [17005, { code: 17005, acronym: 'verdat', valueType: 'enum', name: 'Vertical datum' }],
  [17006, { code: 17006, acronym: 'catbrg', valueType: 'list', name: 'Category of bridge' }],
  [17007, { code: 17007, acronym: 'catfry', valueType: 'enum', name: 'Category of ferry' }],
  [17008, { code: 17008, acronym: 'cathaf', valueType: 'list', name: 'Category of harbour facility' }],
  [17009, { code: 17009, acronym: 'marsys', valueType: 'enum', name: 'Marks navigational - System of' }],
  [17010, { code: 17010, acronym: 'catchp', valueType: 'list', name: 'Category of checkpoint' }],
  [17011, { code: 17011, acronym: 'catlam', valueType: 'enum', name: 'Category of lateral mark' }],
  [17012, { code: 17012, acronym: 'catslc', valueType: 'enum', name: 'Category of shoreline construction' }],
  [17050, { code: 17050, acronym: 'addmrk', valueType: 'list', name: 'additional mark' }],
  [17051, { code: 17051, acronym: 'catbnk', valueType: 'enum', name: 'Category of bank' }],
  [17052, { code: 17052, acronym: 'catnmk', valueType: 'enum', name: 'category of notice mark' }],
  [17055, { code: 17055, acronym: 'clsdng', valueType: 'enum', name: 'class of dangerous cargo' }],
  [17056, { code: 17056, acronym: 'dirimp', valueType: 'list', name: 'direction of impact' }],
  [17057, { code: 17057, acronym: 'disbk1', valueType: 'float', name: 'Distance from notice mark. first' }],
  [17058, { code: 17058, acronym: 'disbk2', valueType: 'float', name: 'Distance from notice mark. second' }],
  [17059, { code: 17059, acronym: 'disipu', valueType: 'float', name: 'Distance of impact. upstream' }],
  [17060, { code: 17060, acronym: 'disipd', valueType: 'float', name: 'Distance of impact. downstream' }],
  [17061, { code: 17061, acronym: 'eleva1', valueType: 'float', name: 'Elevation 1 of surface (m)' }],
  [17062, { code: 17062, acronym: 'eleva2', valueType: 'float', name: 'Elevation 2 of surface (m)' }],
  [17063, { code: 17063, acronym: 'fnctnm', valueType: 'enum', name: 'Function of notice mark' }],
  [17064, { code: 17064, acronym: 'wtwdis', valueType: 'float', name: 'waterway distance' }],
  [17065, { code: 17065, acronym: 'bunves', valueType: 'enum', name: 'bunker vessel. availability' }],
  [17066, { code: 17066, acronym: 'catbrt', valueType: 'list', name: 'category of berth' }],
  [17067, { code: 17067, acronym: 'catbun', valueType: 'list', name: 'category of bunker station' }],
  [17068, { code: 17068, acronym: 'catccl', valueType: 'list', name: 'category of CEMT class' }],
  [17069, { code: 17069, acronym: 'catcom', valueType: 'list', name: 'Category of communication' }],
  [17070, { code: 17070, acronym: 'cathbr', valueType: 'list', name: 'category of harbour area' }],
  [17071, { code: 17071, acronym: 'catrfd', valueType: 'list', name: 'category of refuse dump' }],
  [17072, { code: 17072, acronym: 'cattml', valueType: 'list', name: 'Category of terminal' }],
  [17073, { code: 17073, acronym: 'comctn', valueType: 'string', name: 'Communication' }],
  [17074, { code: 17074, acronym: 'horcll', valueType: 'float', name: 'Horizontal clearance length' }],
  [17075, { code: 17075, acronym: 'horclw', valueType: 'float', name: 'Horizontal clearance width' }],
  [17076, { code: 17076, acronym: 'trshgd', valueType: 'list', name: 'transshipping goods' }],
  [17077, { code: 17077, acronym: 'unlocd', valueType: 'string', name: 'UN location code' }],
  [17078, { code: 17078, acronym: 'catgag', valueType: 'list', name: 'Category of waterway gauge' }],
  [17080, { code: 17080, acronym: 'higwat', valueType: 'float', name: 'Value at relevant high water level' }],
  [17081, { code: 17081, acronym: 'hignam', valueType: 'string', name: 'Name of relevant high water level' }],
  [17082, { code: 17082, acronym: 'lowwat', valueType: 'float', name: 'Value at relevant low water level' }],
  [17083, { code: 17083, acronym: 'lownam', valueType: 'string', name: 'Name of relevant low water level' }],
  [17084, { code: 17084, acronym: 'meawat', valueType: 'float', name: 'Value at relevant mean water level' }],
  [17085, { code: 17085, acronym: 'meanam', valueType: 'string', name: 'Name of relevant mean water level' }],
  [17086, { code: 17086, acronym: 'othwat', valueType: 'float', name: 'Value at other locally relevant water level' }],
  [17087, { code: 17087, acronym: 'othnam', valueType: 'string', name: 'Name of other locally relevant water level' }],
  [17088, { code: 17088, acronym: 'reflev', valueType: 'enum', name: 'Reference gravitational level' }],
  [17089, { code: 17089, acronym: 'sdrlev', valueType: 'string', name: 'Name of Sounding datum reference level' }],
  [17090, { code: 17090, acronym: 'vcrlev', valueType: 'string', name: 'Name of vertical river datum reference level' }],
  [17091, { code: 17091, acronym: 'catvtr', valueType: 'list', name: 'Category of vehicle transfer' }],
  [17092, { code: 17092, acronym: 'cattab', valueType: 'enum', name: 'Category of time and behaviour' }],
  [17093, { code: 17093, acronym: 'schref', valueType: 'string', name: 'Time Schedule Reference' }],
  [17094, { code: 17094, acronym: 'useshp', valueType: 'enum', name: 'Use of Ship' }],
  [17095, { code: 17095, acronym: 'curvhw', valueType: 'float', name: 'Current velocity at high water level' }],
  [17096, { code: 17096, acronym: 'curvlw', valueType: 'float', name: 'Current velocity at low water level' }],
  [17097, { code: 17097, acronym: 'curvmw', valueType: 'float', name: 'Current velocity at mean water level' }],
  [17098, { code: 17098, acronym: 'curvow', valueType: 'float', name: 'Current velocity at other water level' }],
  [17099, { code: 17099, acronym: 'aptref', valueType: 'string', name: 'Average Passing Time Reference' }],
  [17100, { code: 17100, acronym: 'catexs', valueType: 'enum', name: 'Category of exceptional structure' }],
  [17101, { code: 17101, acronym: 'catcbl', valueType: 'enum', name: 'Category of cable' }],
  [17102, { code: 17102, acronym: 'cathlk', valueType: 'list', name: 'Category of hulk' }],
  [17103, { code: 17103, acronym: 'hunits', valueType: 'enum', name: 'Height/length units' }],
  [17104, { code: 17104, acronym: 'watlev', valueType: 'enum', name: 'Water level effect' }],
  [17112, { code: 17112, acronym: 'catwwm', valueType: 'enum', name: 'Category of waterway mark' }],
  [18001, { code: 18001, acronym: 'lg_spd', valueType: 'float', name: 'Maximal permitted speed' }],
  [18002, { code: 18002, acronym: 'lg_spr', valueType: 'list', name: 'speed reference' }],
  [18003, { code: 18003, acronym: 'lg_bme', valueType: 'float', name: 'Maximal permitted beam' }],
  [18004, { code: 18004, acronym: 'lg_lgs', valueType: 'float', name: 'Maximal permitted length' }],
  [18005, { code: 18005, acronym: 'lg_drt', valueType: 'float', name: 'Maximal permitted draught' }],
  [18006, { code: 18006, acronym: 'lg_wdp', valueType: 'float', name: 'Maximal permitted water displacement' }],
  [18007, { code: 18007, acronym: 'lg_wdu', valueType: 'enum', name: 'water displacement unit' }],
  [18008, { code: 18008, acronym: 'lg_rel', valueType: 'list', name: 'related issue' }],
  [18009, { code: 18009, acronym: 'lg_fnc', valueType: 'list', name: 'Function of legal conditions' }],
  [18010, { code: 18010, acronym: 'lg_des', valueType: 'string', name: 'Description of legal conditions' }],
  [18011, { code: 18011, acronym: 'lg_pbr', valueType: 'string', name: 'Publication reference' }],
  [18012, { code: 18012, acronym: 'lc_csi', valueType: 'list', name: 'category of ship (including)' }],
  [18013, { code: 18013, acronym: 'lc_cse', valueType: 'list', name: 'category of ship (excluding)' }],
  [18014, { code: 18014, acronym: 'lc_asi', valueType: 'list', name: 'Assemblies of ship (including)' }],
  [18015, { code: 18015, acronym: 'lc_ase', valueType: 'list', name: 'Assemblies of ship (excluding)' }],
  [18016, { code: 18016, acronym: 'lc_cci', valueType: 'list', name: 'Category of cargo (including)' }],
  [18017, { code: 18017, acronym: 'lc_cce', valueType: 'list', name: 'Category of cargo (excluding)' }],
  [18018, { code: 18018, acronym: 'lc_bm1', valueType: 'float', name: 'Beam range value 1' }],
  [18019, { code: 18019, acronym: 'lc_bm2', valueType: 'float', name: 'Beam range value 2' }],
  [18020, { code: 18020, acronym: 'lc_lg1', valueType: 'float', name: 'Length range value 1' }],
  [18021, { code: 18021, acronym: 'lc_lg2', valueType: 'float', name: 'Length range value 2' }],
  [18022, { code: 18022, acronym: 'lc_dr1', valueType: 'float', name: 'Draught range value 1' }],
  [18023, { code: 18023, acronym: 'lc_dr2', valueType: 'float', name: 'Draught range value 2' }],
  [18024, { code: 18024, acronym: 'lc_sp1', valueType: 'float', name: 'Speed range value 1' }],
  [18025, { code: 18025, acronym: 'lc_sp2', valueType: 'float', name: 'Speed range value 2' }],
  [18026, { code: 18026, acronym: 'lc_wd1', valueType: 'float', name: 'Water displacement range value 1' }],
  [18027, { code: 18027, acronym: 'lc_wd2', valueType: 'float', name: 'Water displacement value 2' }],
  [22031, { code: 22031, acronym: 'ANATR1', valueType: 'string', name: 'Annotation Attribute 1' }],
  [22032, { code: 22032, acronym: 'ANATR2', valueType: 'string', name: 'Annotation Attribute 2' }],
  [22033, { code: 22033, acronym: 'ANATR3', valueType: 'string', name: 'Annotation Attribute 3' }],
  [22034, { code: 22034, acronym: 'ANATR4', valueType: 'string', name: 'Annotation Attribute 4' }],
  [22035, { code: 22035, acronym: 'ANATR5', valueType: 'string', name: 'Annotation Attribute 5' }],
  [22036, { code: 22036, acronym: 'ANATR6', valueType: 'string', name: 'Annotation Attribute 6' }],
  [22037, { code: 22037, acronym: 'ANATR7', valueType: 'string', name: 'Annotation Attribute 7' }],
  [22038, { code: 22038, acronym: 'ANATR8', valueType: 'string', name: 'Annotation Attribute 8' }],
  [22039, { code: 22039, acronym: 'ANATR9', valueType: 'string', name: 'Annotation Attribute 9' }],
  [22040, { code: 22040, acronym: 'ANATRA', valueType: 'string', name: 'Annotation Attribute a' }],
  [22076, { code: 22076, acronym: 'ANTXT1', valueType: 'string', name: 'Annotation Text' }],
  [22135, { code: 22135, acronym: 'ANLYR1', valueType: 'string', name: 'Annotation Layer' }],
  [22227, { code: 22227, acronym: 'NEWTY1', valueType: 'string', name: 'New type 1' }],
  [33066, { code: 33066, acronym: 'shptyp', valueType: 'enum', name: 'Type of Ship' }],
  [40000, { code: 40000, acronym: 'updmsg', valueType: 'string', name: 'Update message' }],
  [50000, { code: 50000, acronym: 'catgeo', valueType: 'enum', name: 'Geometry Primitive Category' }],
]);

/** Reverse lookup: acronym to ATTL code */
export const ATTL_BY_ACRONYM: ReadonlyMap<string, number> = new Map(
  [...S57_ATTRIBUTES.entries()].map(([code, def]) => [def.acronym, code])
);

/** Commonly used ATTL codes as named constants */
export const ATTL = {
  BCNSHP: 2,
  BOYSHP: 4,
  /** @deprecated Not an S-57 attribute; use CATACH (category of anchorage). */
  CATANC: 8,
  CATACH: 8,
  CATBRG: 9,
  CATLMK: 35,
  CATLIT: 37,
  CATOBS: 42,
  CATREA: 56,
  CATWRK: 71,
  COLOUR: 75,
  COLPAT: 76,
  CONDTN: 81,
  CONVIS: 83,
  DRVAL1: 87,
  DRVAL2: 88,
  ELEVAT: 90,
  HEIGHT: 95,
  HORCLR: 98,
  LITCHR: 107,
  LITVIS: 108,
  MARSYS: 109,
  OBJNAM: 116,
  ORIENT: 117,
  QUASOU: 125,
  RESTRN: 131,
  SCAMIN: 133,
  SECTR1: 136,
  SECTR2: 137,
  SIGGRP: 141,
  SIGPER: 142,
  STATUS: 149,
  TOPSHP: 171,
  VALDCO: 174,
  VALSOU: 179,
  VERCLR: 181,
  VERLEN: 186,
  WATLEV: 187,
  INFORM: 102,
  NOBJNM: 301,
} as const;
